//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetoSkyDataBaseEntities : DbContext
    {
        private static NetoSkyDataBaseEntities _context;

        public static NetoSkyDataBaseEntities GetContext()
        {
            if (_context == null)
                _context = new NetoSkyDataBaseEntities();
            return _context;
        }
        public NetoSkyDataBaseEntities()
            : base("name=NetoSkyDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductTypes> ProductTypes { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
